-- Milestone: organizations multi-tenancy, Task 3 — per-organization
-- uniqueness for users.username, users.primary_email, users.employee_id and
-- groups.name.
--
-- Until now these four indexes were GLOBAL, which is the right shape for a
-- single-tenant deployment and exactly the wrong one for a multi-tenant
-- deployment: whichever tenant onboarded `jsmith` first would permanently
-- deny that username to every other tenant. The replacement key is
-- (organization_id, lower(...)) — case-insensitivity is preserved WITHIN an
-- organization, so `jsmith` and `JSmith` still collide inside one tenant.
--
-- The index NAMES are deliberately unchanged. `translateWriteError` in the
-- users and groups repositories matches on exactly these strings to turn a
-- 23505 into a ConflictError; renaming one would silently turn a 409 into a
-- 500 with no test necessarily noticing.
--
-- Security note (finding SEC-L2, docs/archive/audits/carried-findings-
-- verification.md): POST /users' 409 is an existence oracle across org-unit
-- scope precisely BECAUSE these indexes were global. The response-side fix
-- (the 409 says `primaryEmail: not available` and never echoes the
-- submitted value) is already in place and is pinned by
-- test/users.write.spec.ts; this change is defence in depth on top of it,
-- narrowing what the oracle could reveal to within a single tenant, where
-- the caller is already authorised to look.
--
-- Safe on an existing database: every pre-existing row was adopted into the
-- single master organization by 0025_organizations_backfill.sql, so the new
-- key is (master, lower(...)) for all of them — strictly weaker than the
-- old global key, and therefore incapable of failing to build on data that
-- satisfied the old one.
--
-- Generated by drizzle-kit from the schema change in this same commit and
-- then renamed and commented; the DDL below is byte-for-byte what
-- `db:generate` emits, which is what keeps the drift check clean.

DROP INDEX IF EXISTS "groups_name_unique";--> statement-breakpoint
DROP INDEX IF EXISTS "users_primary_email_unique";--> statement-breakpoint
DROP INDEX IF EXISTS "users_username_unique";--> statement-breakpoint
DROP INDEX IF EXISTS "users_employee_id_unique";--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "groups_name_unique" ON "groups" USING btree ("organization_id",lower("name"));--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_primary_email_unique" ON "users" USING btree ("organization_id",lower("primary_email"));--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_username_unique" ON "users" USING btree ("organization_id",lower("username"));--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_employee_id_unique" ON "users" USING btree ("organization_id","employee_id") WHERE "users"."employee_id" IS NOT NULL;
